---
- name: Installs macOS Apps
  hosts: localhost
  gather_facts: no
  tasks:
    - include: playbooks/ansible.yml
      tags: ansible
    - include: playbooks/apps.yml
      tags: apps
    - include: playbooks/zsh.yml
      tags: zsh