---
- name: Install vscode settings file
  ansible.builtin.copy:
    src: vscode/settings.json
    dest: $HOME/Library/Application Support/Code/User/settings.json
    mode: "0644"
  tags:
    - vscode
    - config

- name: Include vscode vars
  ansible.builtin.include_vars: vars/vscode.yml
  tags:
    - vscode
    - config

- name: Install vscode extensions
  ansible.builtin.include_tasks: vscode-extensions-inst.yml
  loop: "{{ visual_studio_code_extensions }}"
  when: visual_studio_code_extensions|length > 0
  tags:
    - vscode
    - config

- name: Uninstall vscode extensions
  ansible.builtin.include_tasks: vscode-extensions-uninst.yml
  loop: "{{ visual_studio_code_extensions_absent }}"
  when: visual_studio_code_extensions_absent|length > 0
  tags:
    - vscode
    - config
