---
- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh/oh-my-zsh.sh
  register: installed
  tags:
    - zsh
    - config

- name: Install oh-my-zsh  # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ ansible_env.HOME + '/.oh-my-zsh' }}"
    update: yes
  when: not installed.stat.exists
  tags:
    - zsh
    - config

- name: Install powerline10k
  community.general.homebrew:
    name: powerlevel10k
  tags:
    - zsh
    - config

- name: Install meslo fonts
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/{{ item }}"
    dest: "/Library/Fonts/{{ item }}"
    mode: "0644"
  with_items:
    - MesloLGS%20NF%20Regular.ttf
    - MesloLGS%20NF%20Bold.ttf
    - MesloLGS%20NF%20Italic.ttf
    - MesloLGS%20NF%20Bold%20Italic.ttf
  tags:
    - zsh
    - config

- name: Create home dire .inc directory
  ansible.builtin.file:
    path: ~/.inc
    state: directory
    mode: "0755"
  tags:
    - zsh
    - config

- name: Install google-cloud-sdk
  ansible.builtin.unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-468.0.0-darwin-arm.tar.gz
    dest: ~/.inc
    remote_src: yes
  tags:
    - zsh
    - config

- name: Install zshrc file
  ansible.builtin.copy:
    mode: "0644"
    src: zsh/zshrc
    dest: ~/.zshrc
  tags:
    - zsh
    - config

- name: Install powerline10k config file
  ansible.builtin.copy:
    mode: "0644"
    src: zsh/p10k.zsh
    dest: ~/.p10k.zsh
  tags:
    - zsh
    - config
