---
# https://formulae.brew.sh/cask/
- name: Installing apps through homebrew (casks)
  community.general.homebrew_cask:
    name:
#      - 1password
      - amazon-chime
      - aws-vault
#      - bitwarden #in app store
      - docker
#      - fantastical
      - firefox
      - google-chrome
      - google-drive
      - inspec
      - iterm2
#      - kaleidoscope
      - keybase
      - keepassxc
      - menumeters
      - microsoft-auto-update
#      - microsoft-edge
#      - microsoft-office
      - microsoft-teams
      - obsidian
      - postman
      - powershell
#      - rancher
#      - signal
#      - slack
#      - tower
#      - transmission
#      - transmit
      - visual-studio-code
#      - vlc
#      - zoom
    state: present
    accept_external_apps: yes

- name: Installing apps through homebrew
  community.general.homebrew:
    name:
      - act
      - awscli
      - azure-cli
      - azure-functions-core-tools@4
      - cloudflare/cloudflare/cloudflared
#      - coreutils
      - gh
      - gnu-tar
      - go
      - granted
#      - gpg
      - hashicorp/tap/terraform-ls
      - helm
      - inframap
      - jq
      - kubectl
      - keybase
      - mas
      - md5sha1sum
#      - nodejs
      - packer
#      - speedtest-cli
      - superbrothers/zsh-kubectl-prompt/zsh-kubectl-prompt
      - turbot/tap/steampipe
      - terraform
#      - timeout
      - tree
      - watch
      - wget
      - yq
      - zsh-autosuggestions
    state: present

- name: Install apps from the App Store
  community.general.mas:
    id:
      - 1352778147 # bitwarden
      - 1295203466 # Microsoft Remote Desktop
      - 823766827  # OneDrive
      - 1230249825 # VMware Remote Console
      - 803453959  # Slack for Desktop
      - 865500966  # feedly. Read more, know more.
      - 1452453066 # hidden bar (menu bar icon organizer)
#      - 1176895641 # spark
#      - 419330170  # moom
#      - 1419729466 # fast vpn
#      - 409907375  # Apple Remote Desktop
      - 1274495053 # Microsoft To Do
#      - 1475387142 # Tailscale
#      - 472226235  # LanScan
      - 409183694  # Keynote
      - 409201541  # Pages
      - 409203825  # Numbers
