---
- name: Set external location for iterm prefs
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "$HOME/.config/iterm2"
    state: present
  tags:
    - iterm2
    - config

- name: Install iterm2 preference file
  ansible.builtin.copy:
    mode: 0644
    src: iterm2/com.googlecode.iterm2.plist
    dest: $HOME/.config/iterm2/com.googlecode.iterm2.plist
  tags:
    - iterm2
    - config
