---
- name: Check if extension {{ item }} is installed
  ansible.builtin.shell: code --list-extensions | grep {{ item }}
  register: vsextension_installed
  changed_when: vsextension_installed.rc != 0
  when: visual_studio_code_extensions|length > 0
  ignore_errors: true
  tags:
    - vscode
    - config

- name: Install missing extension {{ item }}
  ansible.builtin.command: code --install-extension {{ item }}
  register: install_result
  changed_when: install_result.rc == 0
  when:
    - visual_studio_code_extensions|length > 0
    - item != vsextension_installed.stdout
  tags:
    - vscode
    - config
