---
- name: Check if extension is installed
  shell: code --list-extensions | grep {{ item }}
  register: vsextension_installed
  when: visual_studio_code_extensions|length > 0
  ignore_errors: true
  tags:
    - vscode
    - config

- name: Install missing extension {{ item }}
  command: code --install-extension {{ item }}
  when:
    - visual_studio_code_extensions|length > 0
    - item != vsextension_installed.stdout
  tags:
    - vscode
    - config
